name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # 只有打tag时才触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller easygui

      - name: 打包为exe
        run: |
          pyinstaller --onefile Simple today's information.py

      - name: 上传exe到Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Simple today's information.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
